source 'https://github.com/CocoaPods/Specs.git'

target 'CocoaPlayer_Example', :exclusive => true do
  pod "CocoaPlayer", :path => "../"
end

target 'CocoaPlayer_Tests', :exclusive => true do
  pod "CocoaPlayer", :path => "../"

  
end
